--1.D영어영문학과 SQL작성
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, TO_DATE(ENTRANCE_DATE) AS 입학년도
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO =002
ORDER BY 입학년도 ASC;

--2춘 기술대학교 교수중 이름이 세글자가 아닌 교수의 신상
SELECT PROFESSOR_NAME , PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE MOD(LENGTH(PROFESSOR_NAME),2)=0;
--3.춘 기술대학교 남자 교수들의 이름과 나이를 출력하는 SQL문장. 단 나이가 적은 사람에서 많은 순서로 화면 출력
--단 교수중 2000년 이후 출생자는 없음
SELECT PROFESSOR_NAME 교수이름, EXTRACT(YEAR FROM SYSDATE) - (1900+SUBSTR(PROFESSOR_SSN, 1, 2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;
--4.교수들의 이름 중 성을 제외한 이름만 출력하는 문장 작성. 출력헤더는 이름으러
SELECT SUBSTR(PROFESSOR_NAME,2,2)AS 이름
FROM TB_PROFESSOR;
--5.춘 기술대학교의 재수생 입학자를 구하려고 한다. 이때 19살에 입학하면 재수를 하지 않은 것으로 간주
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM TO_DATE(ENTRANCE_DATE)) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6)))!=19 
AND EXTRACT(YEAR FROM TO_DATE(ENTRANCE_DATE)) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6))) >19;

--6. 2020년 크리스마스는 무슨 요일인가
SELECT TO_CHAR(TO_DATE(20201225),'DAY') FROM DUAL;  -----다시 풀기
--7
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYY'), TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'),'YYYY'),
       TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY'), TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY')
FROM DUAL;

--8 춘 기술대학교의 2000년 이후 입학자들은 학번이 A로 시작하게 되어있다. 2000년도 이전 학번을 받은 학생들의 학번과 이름을 보여주라
SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
WHERE TO_NUMBER(EXTRACT (YEAR FROM(ENTRANCE_DATE))) < 2000;

--9.학번이 A517178인 한아름 학생의 학점 총 평점을 구하는 SQL문을 작성하시오. 단 이때 출력 화명의 헤더는 평점이라 하고
--점수는 반올림하여 소수점 이하 한자리만 표시
SELECT ROUND(SUM(POINT)/8,1)
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NO = 'A517178';

--10.학과별 학생수를 구하여 '학과번호','학생수'의 형태로 헤더를 만들어 결과값이 출력되도록 하시오
SELECT DEPARTMENT_NO AS 학과번호, COUNT(DEPARTMENT_NO)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11지도 교수를 배정받지 못한 학생의 수를 알아내는 SQL문
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;
--12 학번이 A12113인 김고운 학생의 년도 별 평점을 구하는 SQL문 작성
SELECT SUBSTR(TERM_NO,1,4)AS "년도",ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);
--13 학과 별 휴학생 수를 파악
SELECT DEPARTMENT_NO, COUNT(*)
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--14 춘 대학교에 다니는 동명이인 학생들의 이름 찾기
SELECT STUDENT_NAME AS 동일이름, COUNT(STUDENT_NAME) AS 동명인수
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME)>1;

--15학번이 A112113인 김고운 학생의 년도, 학기 별 평점과 년도 별.......
SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, 5, 2) 학기, POINT, 평균
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';
--GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4),SUBSTR(TERM_NO, 5, 2));

SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, 5, 2) 학기, ROUND(AVG(POINT), 1) 평균
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
ORDER BY 1; 