--1.학생이름과 주소지를 표시하시오. 정렬은 오름차순을
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;
--2. 휴학중인 학생들의 이름과 주민번호를 나이가 적은 순서로 화면에 출력
SELECT STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;
--3 주소지가 강원도나 경기도인 학생들 중 1900년대 학벌을 가진 학생들의 이름과 학번, 주소를 이름의 오름차순 출력
SELECT STUDENT_NAME AS" 학생이름", STUDENT_NO AS "학번", STUDENT_ADDRESS AS "거주지주소",ENTRANCE_DATE
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '강원%' )
AND TO_NUMBER(EXTRACT(YEAR FROM TO_DATE((ENTRANCE_DATE)))) < 2000
ORDER BY STUDENT_NAME;

--4 현재 법학과 교수 중 가장 나이가 많은 사람부터 이름을 확인할 수 있는 SQL문장 작성
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME ='법학과'
ORDER BY PROFESSOR_SSN ASC;

--5 2004년 2학기에 C3118100과목을 수강한 학생들의 학점 조회
SELECT STUDENT_NO, POINT
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE TERM_NO ='200402' AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC;

--6 학생 번호,학생이름,학과이름을 학생이름으로 오름차순 정렬하여 출력하는 SQL문을 작성하시오
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

--7 춘 기술대학교의 과목이름과 과목의 학과이름 출력
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);
--8 과목별 교수이름 찾기.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);
--9. 8번의 결과중 인문사회 계열에 속한 과목의 교수 이름을 찾으려고 한다. 이에 해당하는 과목 이름과 교수 이름을 출력하는 SQL문
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
WHERE CATEGORY LIKE '인문사회';


--10음악학과의 학생들 평점 구하기
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT),1)
FROM TB_STUDENT                  -- 다시 풀기
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY STUDENT_NO;
--11 학교ㅕ에 나오지 안흥ㄴ 학생 내용 작성
SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE STUDENT_NO ='A313047';
--12 2007년도에 '인간관계론'과목을 수강한 학생 찾기
SELECT DISTINCT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE SUBSTR(TERM_NO,1,4) = '2007' AND CLASS_NAME = '인간관계론';
--13.예체능 계열 과목 중 과목 담당교수를 한 명도 배정받디 못한 과목을 찾아 그 과목 이름과 학과 이름을 출력하는 SQL문 작성
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
     LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
     LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
      AND PROFESSOR_NO IS NULL;
--14 춘 기술대학 서반ㅇㅏ어학과 학생들의 지도교수 게시
SELECT STUDENT_NAME AS 학생이름, PROFESSOR_NAME AS 지도교수
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과';

SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT S
     LEFT JOIN TB_PROFESSOR ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
     JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;-- 다시 풀기

--15. 휴학생이 아닌 학생 중 평점이 4.0이상인 학생들 찾아 출력
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, AVG(POINT)
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4;

--16 환경조경하고가 전공과목들의 고목별 평ㄹ점 파악 SQL
SELECT CLASS_NO,CLASS_NAME, AVG(POINT)
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)  
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)-- 다시풀기
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME;
                    
--17 춘 기술대학교에 다니고 있는 최경희 학생과 같은 과 학생들의 이름과 주소 출력
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = 038;

--18 국어국문학과에서 총 평점이 가장 높은 학생의 이름과 학번을 표시하는 SQL문 작성
SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT)
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO) -- 다시풀기
WHERE DEPARTMENT_NAME ='국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME;
--HAVING AVG(POINT) = (SELECT MAX(AVG(POINT))
--                     FROM 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)        
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT))
                     FROM TB_GRADE
                     JOIN TB_STUDENT USING(STUDENT_NO)
                     JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
                     WHERE DEPARTMENT_NAME = '국어국문학과'
                     GROUP BY STUDENT_NO);
                     
--19 춘 기술대학교의 '환경조경학과'가 속한 같은 계열 학과들의 학과 별 전공과목 평점을 파악하기 위한 SQL문
SELECT DEPARTMENT_NAME, ROUND(AVG(POINT),1)
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = (SELECT CATEGORY
                  FROM TB_DEPARTMENT
                  WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME;