-- 사용자 계정 생성
CREATE USER c##JH IDENTIFIED BY JH;

-- 접속 권한 및 테이블 생성 권한 부여
GRANT CONNECT, RESOURCE TO c##JH;

-- 테이블스페이스 설정
ALTER USER C##JH DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

DROP TABLE TEST;

CREATE TABLE TEST(
 TNO NUMBER PRIMARY KEY,
 TNAME VARCHAR2(100) NOT NULL,
 TDATE DATE DEFAULT SYSDATE NOT NULL
);